//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Card_management_system.DataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string cardnumber { get; set; }
        public int balance { get; set; }
        public Nullable<int> cardid { get; set; }
    
        public virtual Cards Cards { get; set; }
        public virtual Users Users { get; set; }
    }
}
