//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Card_management_system.DataApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int id { get; set; }
        public int senderid { get; set; }
        public int recipientid { get; set; }
        public decimal moneysum { get; set; }
        public string sendercardnum { get; set; }
        public string recipientcardnum { get; set; }
        public Nullable<System.DateTime> transactiondata { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
